WITH tabela1 AS (
    SELECT 
        CAST(SALESORDERID AS INT) AS ORDER_ID,
        CAST(SALESORDERDETAILID AS VARCHAR) AS DETAIL_ID,
        CAST(CARRIERTRACKINGNUMBER AS VARCHAR) AS TRACKING_NUMBER,
        CAST(ORDERQTY AS INT) AS QTY,
        CAST(PRODUCTID AS INT) AS PRODUCT_ID,
        CAST(SPECIALOFFERID AS INT) AS SPECIAL_OFFERID,
        CAST(UNITPRICE AS INT) AS UNIT_PRICE,
        CAST(UNITPRICEDISCOUNT AS FLOAT) AS PRICE_DISCOUNT,
        CAST(ROWGUID AS VARCHAR) AS ROW_GUID,
        CAST(MODIFIEDDATE AS DATE) AS MODIFIED_DATE
    FROM {{ source('erp', 'SALESORDERDETAIL') }}
),
tabela2 AS (
    SELECT 
        CAST(PRODUCTID AS INT) AS PRODUCT_ID,
        CAST(NAME AS VARCHAR) AS NAME,
        CAST(PRODUCTNUMBER AS VARCHAR) AS PRODUCTNUMBER,
        CAST(MAKEFLAG AS VARCHAR) AS MAKE_FLAG,
        CAST(COLOR AS VARCHAR) AS COLOR,
        CAST(SAFETYSTOCKLEVEL AS INT) AS STOCK_LEVEL,
        CAST(SIZE AS VARCHAR) AS SIZE,
        CAST(STANDARDCOST AS FLOAT) AS STANDARD_COST,
        CAST(PRODUCTSUBCATEGORYID AS INT) AS SUBCATEGORYID,
        CAST(PRODUCTMODELID AS VARCHAR) AS PRODUCT_MODELID
    FROM {{ source('erp', 'PRODUCT') }}
)

SELECT 
    tabela1.ORDER_ID,
    tabela1.DETAIL_ID,
    tabela1.TRACKING_NUMBER,
    tabela1.QTY,
    tabela1.PRODUCT_ID AS ORDER_PRODUCT_ID, -- Renomeado
    tabela1.SPECIAL_OFFERID,
    tabela1.UNIT_PRICE,
    tabela1.PRICE_DISCOUNT,
    tabela1.ROW_GUID,
    tabela1.MODIFIED_DATE,
    tabela2.PRODUCT_ID AS PRODUCT_PRODUCT_ID, -- Renomeado
    tabela2.NAME,
    tabela2.PRODUCTNUMBER,
    tabela2.MAKE_FLAG,
    tabela2.COLOR,
    tabela2.STOCK_LEVEL,
    tabela2.SIZE,
    tabela2.STANDARD_COST,
    tabela2.SUBCATEGORYID,
    tabela2.PRODUCT_MODELID
FROM tabela1 
LEFT JOIN tabela2 ON tabela1.PRODUCT_ID = tabela2.PRODUCT_ID
