WITH 
    tabela2 AS (
        SELECT 
            CAST(BUSINESSENTITYID AS INT) AS BUSINESS_ENTITY_ID,
            CAST(PERSONTYPE AS VARCHAR(2)) AS PERSON_TYPE,
            CAST(NAMESTYLE AS varchar) AS NAME_STYLE,
            CAST(TITLE AS VARCHAR(50)) AS TITLE,
            CAST(FIRSTNAME AS VARCHAR(50)) AS FIRST_NAME,
            CAST(MIDDLENAME AS VARCHAR(50)) AS MIDDLE_NAME,
            CAST(LASTNAME AS VARCHAR(50)) AS LAST_NAME,
            CAST(SUFFIX AS VARCHAR(10)) AS SUFFIX,
            CAST(EMAILPROMOTION AS INT) AS EMAIL_PROMOTION
        FROM {{ source('erp', 'PERSON') }}
    ),
    tabela1 AS (
        SELECT 
            CAST(BUSINESSENTITYID AS INT) AS BUSINESS_ENTITY_ID,
            CAST(TERRITORYID AS INT) AS TERRITORY_ID,
            CAST(SALESQUOTA AS DECIMAL(18,2)) AS SALES_QUOTA,
            CAST(BONUS AS DECIMAL(18,2)) AS BONUS,
            CAST(COMMISSIONPCT AS DECIMAL(5,4)) AS COMMISSION_PCT,
            CAST(SALESYTD AS DECIMAL(18,2)) AS SALES_YTD,
            CAST(SALESLASTYEAR AS DECIMAL(18,2)) AS SALES_LAST_YEAR,
            CAST(ROWGUID AS VARCHAR(36)) AS ROW_GUID,
            CAST(MODIFIEDDATE AS DATETIME) AS MODIFIED_DATE
        FROM {{ source('erp', 'SALESPERSON') }}
    )

SELECT 
    t2.BUSINESS_ENTITY_ID AS PERSON_BUSINESS_ENTITY_ID,  -- Renomeado para evitar duplicidade
    t2.PERSON_TYPE,
    t2.NAME_STYLE,
    t2.TITLE,
    t2.FIRST_NAME,
    t2.MIDDLE_NAME,
    t2.LAST_NAME,
    t2.SUFFIX,
    t2.EMAIL_PROMOTION,
    t1.TERRITORY_ID,
    t1.SALES_QUOTA,
    t1.BONUS,
    t1.COMMISSION_PCT,
    t1.SALES_YTD,
    t1.SALES_LAST_YEAR,
    t1.ROW_GUID,
    t1.MODIFIED_DATE
FROM tabela2 t2
JOIN tabela1 t1 
    ON t2.BUSINESS_ENTITY_ID = t1.BUSINESS_ENTITY_ID
